import { USER_ENDPOINT } from "@/constant/constant";

const GET = {
  GET_JOBS: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/jobs`,
  GET_JOB_ID: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job`, // jobid after
  JOB_REQUEST: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job/requests`,
};

const POST = {
  CREATE_JOB: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job`,
};

const PUT = {
  UPDATE_JOB: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job`,
  JOB_APPROVAL: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job/approve`,
  MAKE_COMPLETE: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job/complete`,
  PUBLISH_JOB: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job/publish`
};

const DELETE = {
  JOB: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/job`,
};

export { GET, POST, PUT, DELETE };
