import { USER_ENDPOINT } from "@/constant/constant";

const REVIEW_GET_API = {
  VIEW_WORKER_RATINGS: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/rating`,
  STATS: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/rating/stats`,
  SELF_RATING: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/rating/self`,
};

const REVIEW_POST_API = {
  SUBMIT_WORKER_RATING: `${USER_ENDPOINT.CUSTOMER_ENDPOINT}/rating`,
};

export { REVIEW_GET_API, REVIEW_POST_API };
