import { ENDPOINT } from "@/constant/constant";

const JOB_GET_API = {
  JOB_LIST: `${ENDPOINT.WORKER_ENPOINT}/jobs`,
  JOB_BOOKMARK_LIST: `${ENDPOINT.WORKER_ENPOINT}/jobs/bookmark`,
  JOB_CURRENT_LIST: `${ENDPOINT.WORKER_ENPOINT}/jobs/current-job`,
  JOB_DETAIL: `${ENDPOINT.WORKER_ENPOINT}/job`,
};

const JOB_PUT_API = {
  UPDATE_JOB_STATUS: `${ENDPOINT.WORKER_ENPOINT}/job`,
  UPDATE_TASK_STATUS: `${ENDPOINT.WORKER_ENPOINT}/job/task`,
};

const JOB_POST_API = {
  MAKE_BOOKMARK_JOB: `${ENDPOINT.WORKER_ENPOINT}/job/bookmark`,
  MAKE_REQUEST_JOB: `${ENDPOINT.WORKER_ENPOINT}/job/request`,
};

const JOB_DELETE_API = {
  REMOVE_BOOKMARKED: `${ENDPOINT.WORKER_ENPOINT}/job/bookmark/remove`,
};

export { JOB_GET_API, JOB_POST_API, JOB_PUT_API, JOB_DELETE_API };
